### ISSUE TITLE
Option to exclude certain filetypes

### ISSUE THREAD

**Issue by jez9999** [DmitryDorofeev/vscode-empty-indent#1]
It would be useful to have an option to exclude certain filetypes; for example, often in Markdown files I want to have 2 spaces at the end of a line to force a newline, so I'd like to exclude `.md` files from having empty-indent run on save.

**Comment by DmitryDorofeev** [comment]
Done!
version 0.2.0

**Comment by jez9999** [comment]
@DmitryDorofeev A couple of things:
- You have to close and restart VS Code for the changed settings to take effect - they should probably kick in when settings are updated.
- When you exclude a file type, it also disables the whitespace highlighting for that file.  I would still like the highlighting there, but just no whitespace trimming on save.  Maybe there could be a separate exclude list for the highlighting?
